#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RedDotId {
    AchievementFinish,
    ActivityNoviceTab,
    ActivityJieXiKaPhoto,
    V3a7Anniversary3ActBpSubTask,
    V3a7Anniversary3ActBpBonus,
    BattlePassBonus,
    BattlePassSpBonus,
    BattlePassTask,
    CommandStationBonus,
    DailyTask,
    MailBtn,
    PlayerChangeBgItemNew,
    RoomBlockPackage,
    RoomBuildingPlace,
    RoomCharacterFaithFull,
    RoomCharacterFaithGetFull,
    RoomProductionFull,
    StoreChargeGoodsRead,
    StoreGoodsRead,
    StoreTab,
    TeachingSystem,
    TradeOrderFulfillable,
    TurnbackBattlePassBonus,
    TurnbackBattlePassTask,
    TurnbackDailyBonus,
    TurnbackLegacyTask,
    TurnbackOnceBonus,
    TurnbackSignIn,
    WeeklyTask,
}

impl RedDotId {
    pub const fn id(self) -> i32 {
        match self {
            // mirrors Lua RedDotEnum.DotNode
            Self::AchievementFinish => 1108,
            Self::ActivityNoviceTab => 1010,
            Self::ActivityJieXiKaPhoto => 1057,
            Self::V3a7Anniversary3ActBpSubTask => 3705,
            Self::V3a7Anniversary3ActBpBonus => 3708,
            Self::BattlePassBonus => 1047,
            Self::BattlePassSpBonus => 2204,
            Self::BattlePassTask => 1027,
            Self::CommandStationBonus => 3007,
            Self::DailyTask => 1000,
            Self::MailBtn => 1002,
            Self::PlayerChangeBgItemNew => 1701,
            Self::RoomBlockPackage => 1023,
            Self::RoomBuildingPlace => 1017,
            Self::RoomCharacterFaithFull => 1026,
            Self::RoomCharacterFaithGetFull => 1042,
            Self::RoomProductionFull => 1013,
            Self::StoreChargeGoodsRead => 1044,
            Self::StoreGoodsRead => 1043,
            Self::StoreTab => 1003,
            Self::TeachingSystem => 3712,
            Self::TradeOrderFulfillable => 2240,
            Self::TurnbackBattlePassBonus => 3223,
            Self::TurnbackBattlePassTask => 3224,
            Self::TurnbackDailyBonus => 3216,
            Self::TurnbackLegacyTask => 1093,
            Self::TurnbackOnceBonus => 1091,
            Self::TurnbackSignIn => 1092,
            Self::WeeklyTask => 1001,
        }
    }

    pub const fn from_id(id: i32) -> Option<Self> {
        match id {
            1108 => Some(Self::AchievementFinish),
            1010 => Some(Self::ActivityNoviceTab),
            1057 => Some(Self::ActivityJieXiKaPhoto),
            3705 => Some(Self::V3a7Anniversary3ActBpSubTask),
            3708 => Some(Self::V3a7Anniversary3ActBpBonus),
            1047 => Some(Self::BattlePassBonus),
            2204 => Some(Self::BattlePassSpBonus),
            1027 => Some(Self::BattlePassTask),
            3007 => Some(Self::CommandStationBonus),
            1000 => Some(Self::DailyTask),
            1002 => Some(Self::MailBtn),
            1701 => Some(Self::PlayerChangeBgItemNew),
            1023 => Some(Self::RoomBlockPackage),
            1017 => Some(Self::RoomBuildingPlace),
            1026 => Some(Self::RoomCharacterFaithFull),
            1042 => Some(Self::RoomCharacterFaithGetFull),
            1013 => Some(Self::RoomProductionFull),
            1044 => Some(Self::StoreChargeGoodsRead),
            1043 => Some(Self::StoreGoodsRead),
            1003 => Some(Self::StoreTab),
            3712 => Some(Self::TeachingSystem),
            2240 => Some(Self::TradeOrderFulfillable),
            3223 => Some(Self::TurnbackBattlePassBonus),
            3224 => Some(Self::TurnbackBattlePassTask),
            3216 => Some(Self::TurnbackDailyBonus),
            1093 => Some(Self::TurnbackLegacyTask),
            1091 => Some(Self::TurnbackOnceBonus),
            1092 => Some(Self::TurnbackSignIn),
            1001 => Some(Self::WeeklyTask),
            _ => None,
        }
    }
}
