use crate::engine::manager::{
    buff::{BuffChanges, BuffFanoutResult},
    card::CardChanges,
    conduit::ConduitChange,
    contract::ContractChange,
    emitter::EmitterChange,
    entity::EntityChanges,
    eureka::EurekaChanges,
    ex_point::ExPointChanges,
    field::FieldChange,
    gauge::GaugeChange,
    hp::HpChanges,
    injury::InjuryChange,
    shield::ShieldChanges,
    summon::SummonChanges,
    upgrade::UpgradeChange,
};

#[derive(Debug, Clone, PartialEq)]
pub enum BattleChange {
    SkillLifecycle(crate::engine::skill::action::SkillLifecycle),
    Buff(Box<BuffChanges>),
    BuffFanout(Box<BuffFanoutResult>),
    BuffFeatureMarker(crate::engine::manager::buff::BuffMarkerResult),
    EffectMarker(crate::engine::skill::rule::output::EffectMarker),
    SceneChange { scene_id: i32 },
    BuffActTrigger(crate::engine::manager::buff::BuffActTriggerResult),
    BuffActInfoMarker(crate::engine::manager::buff::BuffActInfoMarkerResult),
    Hp(Box<HpChanges>),
    Death(crate::engine::manager::hp::DeathTransition),
    NuoDiKaHit(crate::engine::mechanic::nuo_di_ka::NuoDiKaHit),
    Injury(InjuryChange),
    Shield(Box<ShieldChanges>),
    ExPoint(ExPointChanges),
    Eureka(EurekaChanges),
    Gauge(GaugeChange),
    NuoDiKa(crate::engine::mechanic::nuo_di_ka::NuoDiKaChange),
    Emitter(EmitterChange),
    Entity(Box<EntityChanges>),
    Card(Box<CardChanges>),
    Conduit(ConduitChange),
    Contract(ContractChange),
    Field(FieldChange),
    RaspberryCapacity(Box<crate::engine::skill::buff_act::raspberry::CapacityResult>),
    Summon(SummonChanges),
    Upgrade(UpgradeChange),
    ToughnessRecovered(crate::engine::manager::toughness::ToughnessRecovery),
    UpgradeApplied(Box<crate::engine::manager::upgrade::UpgradeApplied>),
    EntityPromotion(Box<crate::engine::fight::reserve::Promotion>),
    WaveAdvanced(Box<crate::engine::manager::wave::WaveAdvanced>),
}
