[package]
name = "battle_check"
version.workspace = true
edition.workspace = true
publish = false

[features]
private-fixtures = []

[dependencies]
anyhow.workspace = true
battle.workspace = true
battle_preview = { path = "../battle_preview" }
config.workspace = true
protocol.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
