use crate::error::{AppError, ClientErrorAction, CmdError};
use crate::handlers::{
    activity, bgm, bp, charge, chat, collection, command_post, common, critter, dice_hero, dungeon,
    equipment, exploration, fairyland, friends, guide, hero, hero_group, inventory, mail,
    manufacture, misc, odyssey, party, player_card, player_info, player_misc, property, red_dot,
    room, rouge, sign_in, stat, store, story, summon, survival, system, talent, tasks, tower,
    tower_compose, trade, turnback, udimo, user,
};
use crate::net::context::ConnectionContext;
use crate::net::packet::ClientPacket;
use sonettobuf::{CmdId, ServerErrorInfoPush};

//Todo! port from sonetto rs

macro_rules! dispatch {
    ($cmd_id:expr, $ctx:expr, $packet:expr, {
        $($variant:path => $handler:expr),* $(,)?
    }) => {
        match $cmd_id {
            $(
                $variant => $handler($ctx, $packet).await,
            )*
            v => Err(AppError::Cmd(CmdError::UnhandledCmd(v))),
        }
    };
}

pub async fn dispatch_command(ctx: &mut ConnectionContext, req: Vec<u8>) -> Result<(), AppError> {
    let req = ClientPacket::decode(&req)?;
    let cmd_id = match TryInto::<CmdId>::try_into(req.cmd_id as i32) {
        Ok(cmd_id) => cmd_id,
        Err(_) => {
            tracing::warn!("Unregistered command {}; reconnecting client", req.cmd_id);
            ctx.request_disconnect();
            return Ok(());
        }
    };

    tracing::info!("Received Cmd: {:?}", cmd_id);
    let up_tag = req.up_tag;

    let result = dispatch!(cmd_id, ctx, req, {
        CmdId::LoginCmd => system::on_login,
        CmdId::ReconnectCmd => system::on_reconnect,
        CmdId::RenameCmd => system::on_rename,
        CmdId::UpdateClientStatBaseInfoCmd => stat::on_update_client_stat_base_info,
        CmdId::ClientStatBaseInfoCmd => stat::on_client_stat_base_info,
        CmdId::GpuCpuLogCmd => stat::on_gpu_cpu_log,
        CmdId::GetServerTimeCmd => common::on_get_server_time,
        CmdId::GetPlayerInfoCmd => player_info::on_get_player_info,
        CmdId::GetOtherPlayerInfoCmd => player_info::on_get_other_player_info,
        CmdId::GetOpenInfoCmd => player_info::on_get_open_info,
        CmdId::HeroInfoListCmd => player_info::on_hero_info_list,
        CmdId::MarkHeroFavorCmd => hero::on_mark_hero_favor,
        CmdId::UnMarkIsNewCmd => hero::on_unmark_is_new,
        CmdId::UnlockVoiceCmd => hero::on_unlock_voice,
        CmdId::ItemUnlockCmd => hero::on_item_unlock,
        CmdId::UseSkinCmd => hero::on_use_skin,
        CmdId::HeroRedDotReadCmd => hero::on_hero_red_dot_read,
        CmdId::HeroTouchCmd => hero::on_hero_touch,
        CmdId::HeroDefaultEquipCmd => hero::on_hero_default_equip,
        CmdId::GetHeroBirthdayCmd => hero::on_get_hero_birthday,
        CmdId::ChoiceHero3123WeaponCmd => hero::on_choice_hero_3123_weapon,
        CmdId::ChoiceHero3124TalentTreeCmd => hero::on_choice_hero_3124_talent_tree,
        CmdId::CancelHero3124TalentTreeCmd => hero::on_cancel_hero_3124_talent_tree,
        CmdId::ResetHero3124TalentTreeCmd => hero::on_reset_hero_3124_talent_tree,
        CmdId::DestinyRankUpCmd => hero::on_destiny_rank_up,
        CmdId::DestinyLevelUpCmd => hero::on_destiny_level_up,
        CmdId::DestinyStoneUnlockCmd => hero::on_destiny_stone_unlock,
        CmdId::DestinyStoneUseCmd => hero::on_destiny_stone_use,
        CmdId::HeroUpgradeSkillCmd => hero::on_hero_upgrade_skill,
        CmdId::HeroLevelUpCmd => hero::on_hero_level_up,
        CmdId::HeroRankUpCmd => hero::on_hero_rank_up,
        CmdId::SetPortraitCmd => player_info::on_set_portrait,
        CmdId::SetSignatureCmd => player_info::on_set_signature,
        CmdId::SetBirthdayCmd => player_info::on_set_birthday,
        CmdId::SetCharacterAgeCmd => player_info::on_set_character_age,
        CmdId::SetPlayerBgCmd => player_info::on_set_player_bg,
        CmdId::SetMainSceneSkinCmd => property::on_set_main_scene_skin,
        CmdId::SetUiStyleSkinCmd => property::on_set_ui_style_skin,
        CmdId::MarkMainThumbnailCmd => misc::on_mark_main_thumbnail,
        CmdId::SetShowHeroUniqueIdsCmd => player_info::on_set_show_hero_unique_ids,
        CmdId::GetHeroGroupCommonListCmd => hero_group::on_get_hero_group_common_list,
        CmdId::GetHeroGroupListCmd => hero_group::on_get_hero_group_list,
        CmdId::GetHeroGroupSnapshotListCmd => hero_group::on_get_hero_group_snapshot_list,
        CmdId::SetHeroGroupEquipCmd => hero_group::on_set_hero_group_equip,
        CmdId::SetHeroGroupSnapshotCmd => hero_group::on_set_hero_group_snapshot,
        CmdId::ChangeHeroGroupSelectCmd => hero_group::on_change_hero_group_select,
        CmdId::CheckHeroGroupNameCmd => hero_group::on_check_hero_group_name,
        CmdId::UpdateHeroGroupNameCmd => hero_group::on_update_hero_group_name,
        CmdId::UpdateHeroGroupSortCmd => hero_group::on_update_hero_group_sort,
        CmdId::DeleteHeroGroupCmd => hero_group::on_delete_hero_group,
        CmdId::HeroGroupUpdateHeroGroupCmd => hero_group::on_update_hero_group,
        CmdId::GetClothInfoCmd => player_misc::on_get_cloth_info,
        CmdId::GetFairylandInfoCmd => fairyland::on_get_info,
        CmdId::GetCritterBookInfoCmd => critter::on_get_book_info,
        CmdId::GetUdimoInfoCmd => udimo::on_get_info,
        CmdId::MarkCritterBookNewReadCmd => critter::on_mark_book_read,
        CmdId::SetCritterBookBackgroundCmd => critter::on_set_book_background,
        CmdId::SetCritterBookUseSpecialSkinCmd => critter::on_set_book_special_skin,
        CmdId::RecordDialogCmd => fairyland::on_record_dialog,
        CmdId::RecordElementCmd => fairyland::on_record_element,
        CmdId::ResolvePuzzleCmd => fairyland::on_resolve_puzzle,
        CmdId::GetAssistBonusCmd => player_misc::on_get_assist_bonus,
        CmdId::GetPlayerCardInfoCmd => player_card::on_get_player_card_info,
        CmdId::GetOtherPlayerCardInfoCmd => player_card::on_get_other_player_card_info,
        CmdId::SetPlayerCardShowSettingCmd => player_card::on_set_player_card_show_setting,
        CmdId::SetPlayerCardProgressSettingCmd => player_card::on_set_player_card_progress_setting,
        CmdId::SetPlayerCardBaseSettingCmd => player_card::on_set_player_card_base_setting,
        CmdId::SetPlayerCardHeroCoverCmd => player_card::on_set_player_card_hero_cover,
        CmdId::SetPlayerCardThemeCmd => player_card::on_set_player_card_theme,
        CmdId::SetPlayerCardCritterCmd => player_card::on_set_player_card_critter,
        CmdId::SetPlayerCardShowAchievementCmd => player_card::on_set_player_card_show_achievement,
        CmdId::SetPlayerCardBadgeCmd => player_card::on_set_player_card_badge,
        CmdId::GetCurrencyListCmd => inventory::on_get_currency_list,
        CmdId::ExchangeSameCurrencyCmd => inventory::on_exchange_same_currency,
        CmdId::PopExchangeSameCurrencyCmd => inventory::on_pop_exchange_same_currency,
        CmdId::ExchangeDiamondCmd => inventory::on_exchange_diamond,
        CmdId::GetBuyPowerInfoCmd => inventory::on_get_buy_power_info,
        CmdId::BuyPowerCmd => inventory::on_buy_power,
        CmdId::GetItemListCmd => inventory::on_get_item_list,
        CmdId::AutoUseExpirePowerItemCmd => inventory::on_auto_use_expire_power_item,
        CmdId::UsePowerItemCmd => inventory::on_use_power_item,
        CmdId::UsePowerItemListCmd => inventory::on_use_power_item_list,
        CmdId::UseItemCmd => inventory::on_use_item,
        CmdId::UseInsightItemCmd => inventory::on_use_insight_item,
        CmdId::MarkReadSubType21Cmd => inventory::on_mark_read_sub_type21,
        CmdId::GetEquipInfoCmd => equipment::on_get_equip_info,
        CmdId::EquipLockCmd => equipment::on_equip_lock,
        CmdId::EquipStrengthenCmd => equipment::on_equip_strengthen,
        CmdId::EquipBreakCmd => equipment::on_equip_break,
        CmdId::EquipRefineCmd => equipment::on_equip_refine,
        CmdId::EquipDecomposeCmd => equipment::on_equip_decompose,
        CmdId::GetDungeonCmd => dungeon::on_get_dungeon,
        CmdId::MapElementCmd => dungeon::on_map_element,
        CmdId::GetMapElementRecordCmd => dungeon::on_get_map_element_record,
        CmdId::GetPointRewardCmd => dungeon::on_get_point_reward,
        CmdId::GetPuzzleProgressCmd => dungeon::on_get_puzzle_progress,
        CmdId::SavePuzzleProgressCmd => dungeon::on_save_puzzle_progress,
        CmdId::PuzzleFinishCmd => dungeon::on_puzzle_finish,
        CmdId::StartDungeonCmd => dungeon::on_start_dungeon,
        CmdId::RefreshAssistCmd => dungeon::on_refresh_assist,
        CmdId::ReconnectFightCmd => dungeon::on_reconnect_fight,
        CmdId::BeginRoundCmd => dungeon::on_begin_round,
        CmdId::ResetRoundCmd => dungeon::on_reset_round,
        CmdId::UseClothSkillCmd => dungeon::on_use_cloth_skill,
        CmdId::AutoRoundCmd => dungeon::on_auto_round,
        CmdId::FightEndFightCmd => dungeon::on_fight_end_fight,
        CmdId::GetFightRecordGroupCmd => dungeon::on_get_fight_record_group,
        CmdId::GetFightOperCmd => dungeon::on_get_fight_oper,
        CmdId::GetFightCardDeckInfoCmd => dungeon::on_get_fight_card_deck_info,
        CmdId::GetFightCardDeckDetailInfoCmd => dungeon::on_get_fight_card_deck_detail_info,
        CmdId::EntityInfoCmd => dungeon::on_entity_info,
        CmdId::DungeonEndDungeonCmd => dungeon::on_dungeon_end_dungeon,
        CmdId::CoverDungeonRecordCmd => dungeon::on_cover_dungeon_record,
        CmdId::DungeonInstructionDungeonInfoCmd => dungeon::on_instruction_dungeon_info,
        CmdId::InstructionDungeonOpenCmd => dungeon::on_instruction_dungeon_open,
        CmdId::InstructionDungeonRewardCmd => dungeon::on_instruction_dungeon_reward,
        CmdId::InstructionDungeonFinalRewardCmd => dungeon::on_instruction_dungeon_final_reward,
        CmdId::GetSummonInfoCmd => summon::on_get_summon_info,
        CmdId::GetSummonProgressRewardsCmd => summon::on_get_summon_progress_rewards,
        CmdId::PopUpRecommendWindowCmd => summon::on_pop_up_recommend_window,
        CmdId::SummonQueryTokenCmd => summon::on_summon_query_token,
        CmdId::SummonCmd => summon::on_summon,
        CmdId::ChooseEnhancedPoolHeroCmd => summon::on_choose_enhanced_pool_hero,
        CmdId::ChooseMultiUpHeroCmd => summon::on_choose_multi_up_hero,
        CmdId::LogoutCmd => user::on_logout,
        CmdId::DebugLogoutCmd => user::on_debug_logout,
        CmdId::GetAllMailsCmd => mail::on_get_all_mails,
        CmdId::ReadMailCmd => mail::on_read_mail,
        CmdId::ReadMailBatchCmd => mail::on_read_mail_batch,
        CmdId::MailLockCmd => mail::on_mail_lock,
        CmdId::DeleteMailBatchCmd => mail::on_delete_mail_batch,
        CmdId::MarkMailJumpCmd => mail::on_mark_mail_jump,
        CmdId::GetGuideInfoCmd => guide::on_get_guide_info,
        CmdId::FinishGuideCmd => guide::on_finish_guide,
        CmdId::GetSimplePropertyCmd => property::on_get_simple_property,
        CmdId::SetSimplePropertyCmd => property::on_set_simple_property,
        CmdId::GetSignInInfoCmd => sign_in::on_get_sign_in_info,
        CmdId::SignInCmd => sign_in::on_sign_in,
        CmdId::SignInHistoryCmd => sign_in::on_sign_in_history,
        CmdId::SignInAddupCmd => sign_in::on_sign_in_addup,
        CmdId::SignInTotalRewardCmd => sign_in::on_sign_in_total_reward,
        CmdId::SignInTotalRewardAllCmd => sign_in::on_sign_in_total_reward_all,
        CmdId::GetRedDotInfosCmd => red_dot::on_get_red_dot_infos,
        CmdId::ShowRedDotCmd => red_dot::on_show_red_dot,
        CmdId::PartyServerListCmd => party::on_party_server_list,
        CmdId::GetActivityInfosCmd => activity::on_get_activity_infos,
        CmdId::GetActivityInfosWithParamCmd => activity::on_get_activity_infos_with_param,
        CmdId::ActivityNewStageReadCmd => activity::on_activity_new_stage_read,
        CmdId::UnlockPermanentCmd => activity::on_unlock_permanent,
        CmdId::MarkUnlockNewPhotoRedDotCmd => activity::on_mark_unlock_new_photo_red_dot,
        CmdId::Act1000GetInfoCmd => activity::on_act1000_get_info,
        CmdId::Act1001GetInfoCmd => activity::on_act1001_get_info,
        CmdId::Get101InfosCmd => activity::on_get_101_infos,
        CmdId::Get106InfosCmd => activity::on_get_106_infos,
        CmdId::Get108InfosCmd => activity::on_get_108_infos,
        CmdId::GetAct109InfoCmd => activity::on_get_act109_info,
        CmdId::Get111InfosCmd => activity::on_get_111_infos,
        CmdId::Get112InfosCmd => activity::on_get_112_infos,
        CmdId::GetAct113InfoCmd => activity::on_get_act113_info,
        CmdId::Get114InfosCmd => activity::on_get_114_infos,
        CmdId::GetAct115InfoCmd => activity::on_get_act115_info,
        CmdId::Get116InfosCmd => activity::on_get_116_infos,
        CmdId::GetAct120InfoCmd => activity::on_get_act120_info,
        CmdId::Get121InfosCmd => activity::on_get_121_infos,
        CmdId::GetAct122InfosCmd => activity::on_get_act122_infos,
        CmdId::Get101BonusCmd => activity::on_get_101_bonus,
        CmdId::Get101SpBonusCmd => activity::on_get_101_sp_bonus,
        CmdId::Get104InfosCmd => activity::on_get_104_infos,
        CmdId::MarkEpisodeAfterStoryCmd => activity::on_mark_episode_after_story,
        CmdId::MarkActivity104StoryCmd => activity::on_mark_activity104_story,
        CmdId::MarkPopSummaryCmd => activity::on_mark_pop_summary,
        CmdId::GetAct186InfoCmd => activity::on_get_act186_info,
        CmdId::GetAct186SpBonusInfoCmd => activity::on_get_act186_sp_bonus_info,
        CmdId::AcceptAct186SpBonusCmd => activity::on_accept_act186_sp_bonus,
        CmdId::GetAct189InfoCmd => activity::on_get_act189_info,
        CmdId::GetAct189OnceBonusCmd => activity::on_get_act189_once_bonus,
        CmdId::Get199InfoCmd => activity::on_get_199_info,
        CmdId::Act199GainCmd => activity::on_act199_gain,
        CmdId::GetAct172InfoCmd => activity::on_get_act172_info,
        CmdId::GetAct125InfosCmd => activity::on_get_act125_infos,
        CmdId::FinishAct125EpisodeCmd => activity::on_finish_act125_episode,
        CmdId::GetAct146InfosCmd => activity::on_get_act146_infos,
        CmdId::FinishAct146EpisodeCmd => activity::on_finish_act146_episode,
        CmdId::Act146EpisodeBonusCmd => activity::on_act146_episode_bonus,
        CmdId::Get123InfosCmd => activity::on_get_123_infos,
        CmdId::GetAct124InfosCmd => activity::on_get_act124_infos,
        CmdId::Get126InfosCmd => activity::on_get_126_infos,
        CmdId::Get128InfosCmd => activity::on_get_128_infos,
        CmdId::Get129InfosCmd => activity::on_get_129_infos,
        CmdId::Get130InfosCmd => activity::on_get_130_infos,
        CmdId::Get131InfosCmd => activity::on_get_131_infos,
        CmdId::Get132InfosCmd => activity::on_get_132_infos,
        CmdId::Get133InfosCmd => activity::on_get_133_infos,
        CmdId::Get134InfosCmd => activity::on_get_134_infos,
        CmdId::Get136InfoCmd => activity::on_get_136_info,
        CmdId::Act136SelectCmd => activity::on_act136_select,
        CmdId::Get139InfosCmd => activity::on_get_139_infos,
        CmdId::Get140InfosCmd => activity::on_get_140_infos,
        CmdId::GetAct142InfoCmd => activity::on_get_act142_info,
        CmdId::Get144InfosCmd => activity::on_get_144_infos,
        CmdId::Get145InfosCmd => activity::on_get_145_infos,
        CmdId::GetAct147InfosCmd => activity::on_get_act147_infos,
        CmdId::Get148InfoCmd => activity::on_get_148_info,
        CmdId::Get149InfoCmd => activity::on_get_149_info,
        CmdId::Get152InfoCmd => activity::on_get_152_info,
        CmdId::Act152AcceptPresentCmd => activity::on_act152_accept_present,
        CmdId::Get153InfosCmd => activity::on_get_153_infos,
        CmdId::Get154InfosCmd => activity::on_get_154_infos,
        CmdId::Get157InfoCmd => activity::on_get_157_info,
        CmdId::Answer154PuzzleCmd => activity::on_answer154_puzzle,
        CmdId::Get158InfosCmd => activity::on_get_158_infos,
        CmdId::Get159InfosCmd => activity::on_get_159_infos,
        CmdId::Act160GetInfoCmd => activity::on_act160_get_info,
        CmdId::Act160FinishMissionCmd => activity::on_act160_finish_mission,
        CmdId::Act161GetInfoCmd => activity::on_act161_get_info,
        CmdId::Get163InfosCmd => activity::on_get_163_infos,
        CmdId::Act165GetInfoCmd => activity::on_act165_get_info,
        CmdId::Act165ModifyKeywordCmd => activity::on_act165_modify_keyword,
        CmdId::Act165GenerateEndingCmd => activity::on_act165_generate_ending,
        CmdId::Act165RestartCmd => activity::on_act165_restart,
        CmdId::Act165GainMilestoneRewardCmd => activity::on_act165_gain_milestone_reward,
        CmdId::GetAct164InfoCmd => activity::on_get_act164_info,
        CmdId::Get166InfosCmd => activity::on_get_166_infos,
        CmdId::GetAct167InfoCmd => activity::on_get_act167_info,
        CmdId::Get168InfosCmd => activity::on_get_168_infos,
        CmdId::Get169InfoCmd => activity::on_get_169_info,
        CmdId::Get170InfoCmd => activity::on_get_170_info,
        CmdId::Get171InfoCmd => activity::on_get_171_info,
        CmdId::GetAct208InfoCmd => activity::on_get_act208_info,
        CmdId::Act208ReceiveBonusCmd => activity::on_act208_receive_bonus,
        CmdId::GetAct209InfoCmd => activity::on_get_act209_info,
        CmdId::GetAct174InfoCmd => activity::on_get_act174_info,
        CmdId::GetAct178InfoCmd => activity::on_get_act178_info,
        CmdId::Get179InfosCmd => activity::on_get_179_infos,
        CmdId::Get180InfosCmd => activity::on_get_180_infos,
        CmdId::Get181InfosCmd => activity::on_get_181_infos,
        CmdId::GetAct182InfoCmd => activity::on_get_act182_info,
        CmdId::Act183GetInfoCmd => activity::on_act183_get_info,
        CmdId::GetAct184InfoCmd => activity::on_get_act184_info,
        CmdId::GetAct185InfoCmd => activity::on_get_act185_info,
        CmdId::Get187InfoCmd => activity::on_get_187_info,
        CmdId::GetAct188InfoCmd => activity::on_get_act188_info,
        CmdId::GetAct190InfoCmd => activity::on_get_act190_info,
        CmdId::GetAct191InfoCmd => activity::on_get_act191_info,
        CmdId::GetAct192InfoCmd => activity::on_get_act192_info,
        CmdId::Act194GetInfosCmd => activity::on_act194_get_infos,
        CmdId::Get196InfoCmd => activity::on_get_196_info,
        CmdId::Act196GainCmd => activity::on_act196_gain,
        CmdId::Get197InfoCmd => activity::on_get_197_info,
        CmdId::Act197RummageCmd => activity::on_act197_rummage,
        CmdId::Act197ExploreCmd => activity::on_act197_explore,
        CmdId::Act198GainCmd => activity::on_act198_gain,
        CmdId::Get201InfoCmd => activity::on_get_201_info,
        CmdId::GetAct203InfoCmd => activity::on_get_act203_info,
        CmdId::GetAct204InfoCmd => activity::on_get_act204_info,
        CmdId::Act205GetInfoCmd => activity::on_act205_get_info,
        CmdId::Act205GetGameInfoCmd => activity::on_act205_get_game_info,
        CmdId::Act205FinishGameCmd => activity::on_act205_finish_game,
        CmdId::Act206GetInfoCmd => activity::on_act206_get_info,
        CmdId::Act206ChooseDirectionCmd => activity::on_act206_choose_direction,
        CmdId::Act206GetBonusCmd => activity::on_act206_get_bonus,
        CmdId::GetAct210InfoCmd => activity::on_get_act210_info,
        CmdId::GetAct211InfoCmd => activity::on_get_act211_info,
        CmdId::GetAct215InfoCmd => activity::on_get_act215_info,
        CmdId::Get217InfosCmd => activity::on_get_217_infos,
        CmdId::GetAct216InfoCmd => activity::on_get_act216_info,
        CmdId::FinishAct216TaskCmd => activity::on_finish_act216_task,
        CmdId::GetAct216OnceBonusCmd => activity::on_get_act216_once_bonus,
        CmdId::Get218InfoCmd => activity::on_get_218_info,
        CmdId::Act218FinishGameCmd => activity::on_act218_finish_game,
        CmdId::Act218AcceptRewardCmd => activity::on_act218_accept_reward,
        CmdId::GetAct220InfoCmd => activity::on_get_act220_info,
        CmdId::Get221InfoCmd => activity::on_get_221_info,
        CmdId::Act221SummonCmd => activity::on_act221_summon,
        CmdId::Act221SelectCmd => activity::on_act221_select,
        CmdId::GetAct223InfoCmd => activity::on_get_act223_info,
        CmdId::GetAct224InfoCmd => activity::on_get_act224_info,
        CmdId::GetAct212InfoCmd => activity::on_get_act212_info,
        CmdId::GetAct225InfoCmd => activity::on_get_act225_info,
        CmdId::GetAct226InfoCmd => activity::on_get_act226_info,
        CmdId::Act212ReceiveBonusCmd => activity::on_act212_receive_bonus,
        CmdId::GetAct228InfoCmd => activity::on_get_act228_info,
        CmdId::Act228FlipGridCmd => activity::on_act228_flip_grid,
        CmdId::Act228GetFinalBonusCmd => activity::on_act228_get_final_bonus,
        CmdId::GetAct229InfoCmd => activity::on_get_act229_info,
        CmdId::StartAct229BattleCmd => activity::on_start_act229_battle,
        CmdId::Act229ResetStageCmd => activity::on_reset_act229_stage,
        CmdId::GetAct231InfoCmd => activity::on_get_act231_info,
        CmdId::GetAct235InfoCmd => activity::on_get_act235_info,
        CmdId::Act240GetInfoCmd => activity::on_act240_get_info,
        CmdId::GetCommandPostInfoCmd => command_post::on_get_command_post_info,
        CmdId::CommandPostCharacterReadCmd => command_post::on_command_post_character_read,
        CmdId::CommandPostEventReadCmd => command_post::on_command_post_event_read,
        CmdId::CommandPostPaperCmd => command_post::on_command_post_paper,
        CmdId::CommandPostDispatchCmd => command_post::on_command_post_dispatch,
        CmdId::CommandPostBonusCmd => command_post::on_command_post_bonus,
        CmdId::FinishCommandPostEventCmd => command_post::on_finish_command_post_event,
        CmdId::CommandPostBonusAllCmd => command_post::on_command_post_bonus_all,
        CmdId::GetTaskInfoCmd => tasks::on_get_task_info,
        CmdId::FinishTaskCmd => tasks::on_finish_task,
        CmdId::FinishAllTaskCmd => tasks::on_finish_all_task,
        CmdId::GetTaskActivityBonusCmd => tasks::on_get_task_activity_bonus,
        CmdId::FinishReadTaskCmd => tasks::on_finish_read_task,
        CmdId::RefreshOnlineTaskCmd => tasks::on_refresh_online_task,
        CmdId::GetAchievementInfoCmd => collection::on_get_achievement_info,
        CmdId::ReadNewAchievementCmd => collection::on_read_new_achievement,
        CmdId::ShowAchievementCmd => collection::on_show_achievement,
        CmdId::GetAntiqueInfoCmd => collection::on_get_antique_info,
        CmdId::GetDialogInfoCmd => collection::on_get_dialog_info,
        CmdId::RecordDialogInfoCmd => collection::on_record_dialog_info,
        CmdId::GetBpInfoCmd => bp::on_get_bp_info,
        CmdId::GetBpBonusCmd => bp::on_get_bp_bonus,
        CmdId::GetSelfSelectBonusCmd => bp::on_get_self_select_bonus,
        CmdId::BpBuyLevelRequsetCmd => bp::on_buy_level,
        CmdId::BpMarkFirstShowCmd => bp::on_bp_mark_first_show,
        CmdId::GetChargeInfoCmd => charge::on_get_charge_info,
        CmdId::GetMonthCardInfoCmd => charge::on_get_month_card_info,
        CmdId::GetMonthCardBonusCmd => charge::on_get_month_card_bonus,
        CmdId::GetChargePushInfoCmd => charge::on_get_charge_push_info,
        CmdId::ReadChargeNewCmd => charge::on_read_charge_new,
        CmdId::GetStoreInfosCmd => store::on_get_store_infos,
        CmdId::BuyGoodsCmd => store::on_buy_goods,
        CmdId::NewOrderCmd => store::on_new_order,
        CmdId::ReadStoreNewCmd => store::on_read_store_new,
        CmdId::LoadFriendInfosCmd => friends::on_load_friend_infos,
        CmdId::GetFriendInfoListCmd => friends::on_get_friend_info_list,
        CmdId::GetRecommendedFriendsCmd => friends::on_get_recommended_friends,
        CmdId::GetApplyListCmd => friends::on_get_apply_list,
        CmdId::GetBlacklistCmd => friends::on_get_blacklist,
        CmdId::RemoveFriendCmd => friends::on_remove_friend,
        CmdId::AddBlacklistCmd => friends::on_add_blacklist,
        CmdId::RemoveBlacklistCmd => friends::on_remove_blacklist,
        CmdId::SearchCmd => friends::on_search,
        CmdId::SendMsgCmd => chat::on_send_msg,
        CmdId::DeleteOfflineMsgCmd => chat::on_delete_offline_msg,
        CmdId::ReportCmd => chat::on_report,
        CmdId::WordTestCmd => chat::on_word_test,
        CmdId::GetStoryCmd => story::on_get_story,
        CmdId::GetStoryFinishCmd => story::on_get_story_finish,
        CmdId::UpdateStoryCmd => story::on_update_story,
        CmdId::GetHeroStoryCmd => story::on_get_hero_story,
        CmdId::GetNecrologistStoryCmd => story::on_get_necrologist_story,
        CmdId::UpdateNecrologistStoryCmd => story::on_update_necrologist_story,
        CmdId::FinishNecrologistStoryModeCmd => story::on_finish_necrologist_story_mode,
        CmdId::GetExploreSimpleInfoCmd => exploration::on_get_explore_simple_info,
        CmdId::GetTowerInfoCmd => tower::on_get_info,
        CmdId::TowerMopUpCmd => tower::on_mop_up,
        CmdId::TowerResetSubEpisodeCmd => tower::on_reset_sub_episode,
        CmdId::StartTowerBattleCmd => tower::on_start_battle,
        CmdId::TowerActiveTalentCmd => tower::on_active_talent,
        CmdId::TowerResetTalentCmd => tower::on_reset_talent,
        CmdId::TowerChangeTalentPlanCmd => tower::on_change_talent_plan,
        CmdId::TowerRenameTalentPlanCmd => tower::on_rename_talent_plan,
        CmdId::TowerComposeGetInfoCmd => tower_compose::on_tower_compose_get_info,
        CmdId::TowerComposeSetModsCmd => tower_compose::on_tower_compose_set_mods,
        CmdId::GetWeekwalkInfoCmd => exploration::on_get_weekwalk_info,
        CmdId::WeekwalkVer2GetInfoCmd => exploration::on_weekwalk_ver2_get_info,
        CmdId::GetBlockPackageInfoRequsetCmd => room::on_get_block_package_info,
        CmdId::HideBlockPackageReddotCmd => room::on_hide_block_package_reddot,
        CmdId::HideBuildingReddotRequsetCmd => room::on_hide_building_reddot,
        CmdId::GetBlockPermanentInfoCmd => room::on_get_block_permanent_info,
        CmdId::GetBuildingInfoCmd => room::on_get_building_info,
        CmdId::UseBlockCmd => room::on_use_block,
        CmdId::UnUseBlockCmd => room::on_unuse_block,
        CmdId::ResetRoomCmd => room::on_reset_room,
        CmdId::SetWaterTypeCmd => room::on_set_water_type,
        CmdId::SetBlockColorCmd => room::on_set_block_color,
        CmdId::GenerateRoadCmd => room::on_generate_road,
        CmdId::DeleteRoadCmd => room::on_delete_road,
        CmdId::AllotCritterCmd => room::on_allot_critter,
        CmdId::AllotVehicleCmd => room::on_allot_vehicle,
        CmdId::UseBuildingCmd => room::on_use_building,
        CmdId::UnUseBuildingCmd => room::on_unuse_building,
        CmdId::GetCharacterInteractionInfoCmd => room::on_get_character_interaction_info,
        CmdId::StartCharacterInteractionCmd => room::on_start_character_interaction,
        CmdId::GetCharacterInteractionBonusCmd => room::on_get_character_interaction_bonus,
        CmdId::GetRoomInfoCmd => room::on_get_room_info,
        CmdId::GetRoomObInfoCmd => room::on_get_room_ob_info,
        CmdId::GetRoomPlanInfoCmd => room::on_get_room_plan_info,
        CmdId::GetRoomPlanDetailsCmd => room::on_get_room_plan_details,
        CmdId::SetRoomPlanCmd => room::on_set_room_plan,
        CmdId::SetRoomPlanNameCmd => room::on_set_room_plan_name,
        CmdId::SetRoomPlanCoverCmd => room::on_set_room_plan_cover,
        CmdId::DeleteRoomPlanCmd => room::on_delete_room_plan,
        CmdId::SwitchRoomPlanCmd => room::on_switch_room_plan,
        CmdId::UseRoomPlanCmd => room::on_use_room_plan,
        CmdId::ShareRoomPlanCmd => room::on_share_room_plan,
        CmdId::GetRoomShareCmd => room::on_get_room_share,
        CmdId::UseRoomShareCmd => room::on_use_room_share,
        CmdId::CopyOtherRoomPlanCmd => room::on_copy_other_room_plan,
        CmdId::DeleteRoomShareCmd => room::on_delete_room_share,
        CmdId::GetRoomLogCmd => room::on_get_room_log,
        CmdId::RoomConfirmCmd => room::on_room_confirm,
        CmdId::RoomRevertCmd => room::on_room_revert,
        CmdId::GetOtherRoomObInfoCmd => room::on_get_other_room_ob_info,
        CmdId::ReadRoomLogNewCmd => room::on_read_room_log_new,
        CmdId::GetRoomThemeCollectionBonusCmd => room::on_get_room_theme_collection_bonus,
        CmdId::ProductionLineInfoCmd => room::on_production_line_info,
        CmdId::StartProductionLineCmd => room::on_start_production_line,
        CmdId::GainProductionLineCmd => room::on_gain_production_line,
        CmdId::ProductionLineLvUpCmd => room::on_production_line_lv_up,
        CmdId::ProductionLineAccelerateCmd => room::on_production_line_accelerate,
        CmdId::RoomLevelUpCmd => room::on_room_level_up,
        CmdId::SetRoomSkinCmd => room::on_set_room_skin,
        CmdId::ReadRoomSkinCmd => room::on_read_room_skin,
        CmdId::UpdateRoomHeroDataCmd => room::on_update_room_hero_data,
        CmdId::GainRoomHeroFaithCmd => room::on_gain_room_hero_faith,
        CmdId::CritterGetInfoCmd => critter::on_critter_get_info,
        CmdId::CritterRenameCmd => critter::on_critter_rename,
        CmdId::LockCritterCmd => critter::on_lock_critter,
        CmdId::ChangeRestCritterCmd => critter::on_change_rest_critter,
        CmdId::GetBgmInfoCmd => bgm::on_get_bgm_info,
        CmdId::SetUseBgmCmd => bgm::on_set_use_bgm,
        CmdId::SetFavoriteBgmCmd => bgm::on_set_favorite_bgm,
        CmdId::ReadBgmCmd => bgm::on_read_bgm,
        CmdId::GetHandbookInfoCmd => misc::on_get_handbook_info,
        CmdId::HandbookReadCmd => misc::on_handbook_read,
        CmdId::GetSettingInfosCmd => misc::on_get_setting_infos,
        CmdId::UpdateSettingInfoCmd => misc::on_update_setting_info,
        CmdId::GetUnlockVoucherInfoCmd => misc::on_get_unlock_voucher_info,
        CmdId::GetPowerMakerInfoCmd => misc::on_get_power_maker_info,
        CmdId::GetRougeOutsideInfoCmd => rouge::on_get_rouge_outside_info,
        CmdId::GetRouge2OutsideInfoCmd => rouge::on_get_rouge2_outside_info,
        CmdId::GetRouge2InfoCmd => rouge::on_get_rouge2_info,
        CmdId::Rouge2GetUnlockCollectionsCmd => rouge::on_rouge2_get_unlock_collections,
        CmdId::SurvivalOutSideGetInfoCmd => survival::on_get_outside_info,
        CmdId::OdysseyGetInfoCmd => odyssey::on_odyssey_get_info,
        CmdId::DiceHeroGetInfoCmd => dice_hero::on_dice_hero_get_info,
        CmdId::DiceHeroEnterStoryCmd => dice_hero::on_dice_hero_enter_story,
        CmdId::DiceHeroGetRewardCmd => dice_hero::on_dice_hero_get_reward,
        CmdId::GetTurnbackInfoCmd => turnback::on_get_turnback_info,
        CmdId::TurnbackFirstShowCmd => turnback::on_turnback_first_show,
        CmdId::TurnbackOnceBonusCmd => turnback::on_turnback_once_bonus,
        CmdId::TurnbackSignInCmd => turnback::on_turnback_sign_in,
        CmdId::GetTurnbackDailyBonusCmd => turnback::on_get_turnback_daily_bonus,
        CmdId::TurnbackBonusPointCmd => turnback::on_turnback_bonus_point,
        CmdId::AcceptAllTurnbackBonusPointCmd => turnback::on_accept_all_turnback_bonus_point,
        CmdId::BuyDoubleBonusCmd => turnback::on_buy_double_bonus,
        CmdId::GetTradeTaskInfoCmd => trade::on_get_trade_task_info,
        CmdId::GetOrderInfoCmd => trade::on_get_order_info,
        CmdId::ReadNewTradeTaskCmd => trade::on_read_new_trade_task,
        CmdId::GetTradeTaskExtraBonusCmd => trade::on_get_trade_task_extra_bonus,
        CmdId::GetTradeSupportBonusCmd => trade::on_get_trade_support_bonus,
        CmdId::TradeLevelUpCmd => trade::on_trade_level_up,
        CmdId::GetManufactureInfoCmd => manufacture::on_get_manufacture_info,
        CmdId::GetFrozenItemInfoCmd => manufacture::on_get_frozen_item_info,
        CmdId::BuyManufactureBuildingCmd => manufacture::on_buy_manufacture_building,
        CmdId::ManuBuildingUpgradeCmd => manufacture::on_manu_building_upgrade,
        CmdId::SelectSlotProductionPlanCmd => manufacture::on_select_slot_production_plan,
        CmdId::ManufactureAccelerateCmd => manufacture::on_manufacture_accelerate,
        CmdId::ReapFinishSlotCmd => manufacture::on_reap_finish_slot,
        CmdId::TalentStyleReadCmd => talent::on_talent_style_read,
        CmdId::PutTalentCubeCmd => talent::on_put_talent_cube,
        CmdId::PutTalentCubeBatchCmd => talent::on_put_talent_cube_batch,
        CmdId::TakeoffAllTalentCubeCmd => talent::on_takeoff_all_talent_cube,
        CmdId::RenameTalentTemplateCmd => talent::on_rename_talent_template,
        CmdId::HeroTalentUpCmd => talent::on_hero_talent_up,
        CmdId::PutTalentSchemeCmd => talent::on_put_talent_scheme,
        CmdId::HeroTalentStyleStatCmd => talent::on_hero_talent_style_stat,
        CmdId::UnlockTalentStyleCmd => talent::on_unlock_talent_style,
        CmdId::UseTalentStyleCmd => talent::on_use_talent_style,
        CmdId::UseTalentTemplateCmd => talent::on_use_talent_template,
    });

    match result {
        Ok(()) => Ok(()),
        Err(error) => handle_command_error(ctx, cmd_id, up_tag, error).await,
    }
}

async fn handle_command_error(
    ctx: &mut ConnectionContext,
    cmd_id: CmdId,
    up_tag: u8,
    error: AppError,
) -> Result<(), AppError> {
    let is_unhandled = matches!(error, AppError::Cmd(CmdError::UnhandledCmd(_)));
    let action = error.client_action();
    let result_code = match action {
        ClientErrorAction::Reply(code) | ClientErrorAction::Reconnect(code) => code,
    };
    let client_message = match (&error, action) {
        (AppError::Cmd(CmdError::UnhandledCmd(_)), _) => {
            format!("{cmd_id:?} is not implemented")
        }
        (_, ClientErrorAction::Reply(_)) => format!("{cmd_id:?}: {error}"),
        (_, ClientErrorAction::Reconnect(_)) => {
            format!("{cmd_id:?} failed; reconnecting to restore client state")
        }
    };
    match action {
        ClientErrorAction::Reply(_) => tracing::warn!(
            command = ?cmd_id,
            result_code = result_code.id(),
            "Request rejected: {error}"
        ),
        ClientErrorAction::Reconnect(_) => tracing::error!(
            command = ?cmd_id,
            result_code = result_code.id(),
            "Command failed; reconnecting client: {error}"
        ),
    }

    ctx.notify(
        CmdId::ServerErrorInfoPushCmd,
        ServerErrorInfoPush {
            msg: Some(client_message),
            is_alert: Some(!is_unhandled),
        },
    )
    .await?;
    ctx.send_empty_reply(cmd_id, Vec::new(), result_code.id(), up_tag)
        .await?;
    if matches!(action, ClientErrorAction::Reconnect(_)) {
        ctx.request_disconnect();
    }
    Ok(())
}
