use std::{
    collections::BTreeMap,
    fs::{self, OpenOptions},
    io::Write,
    path::Path,
};

use anyhow::{Context, Result};

use super::model::{Buff, Skill, Subject};

pub(crate) fn overview(output: &Path, heroes: bool, psychubes: bool, stages: bool) -> Result<()> {
    let mut text = String::from(
        "# Battle support\n\nGenerated by `battle_check`; do not hand-edit generated pages. Registry presence, semantic support, and capture observation are separate claims. A semantically ready config closure is not capture parity.\n\n",
    );
    if heroes {
        text.push_str("- [Heroes](hero-support.md)\n");
    }
    if psychubes {
        text.push_str("- [Psychubes](psychube-support.md)\n");
    }
    if stages {
        text.push_str("- [Stages](stage-support.md)\n");
    }
    write(output.join("battle-support.md"), &text)
}

pub(crate) fn heroes(output: &Path, subjects: &[Subject]) -> Result<()> {
    let links = Links::load(output)?;
    fs::create_dir_all(output.join("hero-support")).context("create hero report directory")?;
    let mut index = String::from(
        "# Hero support\n\nEach Base or Euphoria row has an independently scanned closure. `Unexercised` means configuration was scanned without an authoritative retained capture; it does not mean unsupported.\n\n| Hero | Variant | Registry/semantic state | Capture | Issue / PR | Detail |\n|---|---|---|---|---|---|\n",
    );
    for subject in subjects {
        let detail = format!("hero-support/{}-{}.md", subject.id, subject.slug);
        for variant in &subject.variants {
            let key = variant.source_id.map_or_else(
                || format!("hero:{}", subject.id),
                |facet| format!("hero:{}:euphoria:{facet}", subject.id),
            );
            index.push_str(&format!(
                "| {} {} | {}{} | {} | {} | {} | [open]({}) |\n",
                subject.id,
                escape(&subject.name),
                escape(&variant.label),
                variant.source_id.map_or_else(String::new, |id| format!(
                    " ({id}, rank {})",
                    variant.source_rank.unwrap_or_default()
                )),
                variant.scan.status(),
                variant.observation,
                links.render(&key),
                detail,
            ));
        }
        write(output.join(&detail), &detail_page("Hero", subject, &links))?;
    }
    write(output.join("hero-support.md"), &index)
}

pub(crate) fn psychubes(output: &Path, subjects: &[Subject]) -> Result<()> {
    let links = Links::load(output)?;
    fs::create_dir_all(output.join("psychube-support"))
        .context("create psychube report directory")?;
    let mut index = String::from(
        "# Psychube support\n\nThe highest configured amplification is scanned. Capture observation remains a separate claim.\n\n| Psychube | Scan | Capture | Issue / PR | Detail |\n|---|---|---|---|---|\n",
    );
    for subject in subjects {
        let detail = format!("psychube-support/{}-{}.md", subject.id, subject.slug);
        index.push_str(&format!(
            "| {} {} | {} | {} | {} | [open]({}) |\n",
            subject.id,
            escape(&subject.name),
            subject.variants[0].scan.status(),
            subject.variants[0].observation,
            links.render(&format!("psychube:{}", subject.id)),
            detail,
        ));
        write(
            output.join(&detail),
            &detail_page("Psychube", subject, &links),
        )?;
    }
    write(output.join("psychube-support.md"), &index)
}

pub(crate) fn stages(output: &Path, subjects: &[Subject]) -> Result<()> {
    let links = Links::load(output)?;
    fs::create_dir_all(output.join("stage-support")).context("create stage report directory")?;
    let mut chapters = BTreeMap::<i32, Vec<&Subject>>::new();
    for subject in subjects {
        chapters
            .entry(subject.chapter_id.unwrap_or_default())
            .or_default()
            .push(subject);
    }
    let mut chapters = chapters.into_iter().collect::<Vec<_>>();
    chapters.sort_by_key(|(chapter, _)| chapter_order(*chapter));
    let mut index = String::from("# Stage support\n\n## Chapters\n\n### Main story\n\n");
    for (chapter, _) in chapters
        .iter()
        .filter(|(chapter, _)| (101..=113).contains(chapter))
    {
        index.push_str(&format!(
            "- [{}](#{})\n",
            chapter_label(*chapter),
            chapter_anchor(*chapter)
        ));
    }
    index.push_str("\n### Hard mode\n\n");
    for (chapter, _) in chapters
        .iter()
        .filter(|(chapter, _)| (201..=213).contains(chapter))
    {
        index.push_str(&format!(
            "- [{}](#{})\n",
            chapter_label(*chapter),
            chapter_anchor(*chapter)
        ));
    }
    index.push_str("\n<details>\n<summary>Other config chapters</summary>\n\n");
    for (chapter, _) in chapters
        .iter()
        .filter(|(chapter, _)| !(101..=113).contains(chapter) && !(201..=213).contains(chapter))
    {
        index.push_str(&format!(
            "- [{}](#{})\n",
            chapter_label(*chapter),
            chapter_anchor(*chapter)
        ));
    }
    index.push_str("\n</details>\n");
    for (chapter, stages) in chapters {
        index.push_str(&format!(
            "\n## {}\n\n| Stage | Config battle | Scan | Capture | Issue / PR | Detail |\n|---|---|---|---|---|---|\n",
            chapter_label(chapter),
        ));
        for subject in stages {
            let detail = format!("stage-support/{}-{}.md", subject.id, subject.slug);
            let variant = &subject.variants[0];
            index.push_str(&format!(
                "| {} {} | {} | {} | {} | {} | [open]({}) |\n",
                subject.id,
                escape(&subject.name),
                variant.source_id.unwrap_or_default(),
                variant.scan.status(),
                variant.observation,
                links.render(&format!("stage:{}", subject.id)),
                detail,
            ));
            write(output.join(&detail), &detail_page("Stage", subject, &links))?;
        }
    }
    write(output.join("stage-support.md"), &index)
}

fn detail_page(kind: &str, subject: &Subject, links: &Links) -> String {
    let mut text = format!(
        "# {kind} {} — {}\n\nGenerated configuration closure. Capture references are evidence that an ID appeared on retained wire data; they are not by themselves proof of full packet parity.\n\n",
        subject.id, subject.name
    );
    for variant in &subject.variants {
        let key = match (kind, variant.source_id) {
            ("Hero", Some(facet)) => format!("hero:{}:euphoria:{facet}", subject.id),
            ("Hero", None) => format!("hero:{}", subject.id),
            ("Psychube", _) => format!("psychube:{}", subject.id),
            _ => format!("stage:{}", subject.id),
        };
        text.push_str(&format!(
            "## {}\n\n- Source ID: {}\n- Configured rank: {}\n- Semantic closure: **{}**\n- Capture observation: **{}**\n- Issue / PR: {}\n- Skills: {}\n- Buffs: {}\n- Exact gaps: {}\n\n",
            variant.label,
            variant.source_id.map_or_else(|| "Base".to_owned(), |id| id.to_string()),
            variant.source_rank.map_or_else(|| "—".to_owned(), |rank| rank.to_string()),
            variant.scan.status(),
            variant.observation,
            links.render(&key),
            variant.scan.skills.len(),
            variant.scan.buffs.len(),
            variant.scan.gaps,
        ));
        for skill in &variant.scan.skills {
            render_skill(&mut text, skill);
        }
        if !variant.scan.buffs.is_empty() {
            text.push_str("### Buffs\n\n");
            for buff in &variant.scan.buffs {
                render_buff(&mut text, buff);
            }
        }
        if !variant.scan.errors.is_empty() {
            text.push_str("### Exact diagnostics\n\n");
            for error in &variant.scan.errors {
                text.push_str(&format!("- `{}`\n", inline(error)));
            }
            text.push('\n');
        }
        if !variant.scan.warnings.is_empty() {
            text.push_str("### Warnings\n\n");
            for warning in &variant.scan.warnings {
                text.push_str(&format!("- `{}`\n", inline(warning)));
            }
            text.push('\n');
        }
    }
    text
}

fn render_skill(text: &mut String, skill: &Skill) {
    text.push_str(&format!(
        "### Skill {} — {}\n\n- Effect: {}\n- Mechanical template: {}\n- Template values (`effDesc`): `{}`\n- Effect metadata: `{}`\n- Art text: {}\n- Capture: {}\n\n",
        skill.id,
        escape(&skill.name),
        skill.effect_id,
        prose(&skill.mechanic_template),
        inline(&skill.description),
        inline(&skill.effect_metadata),
        prose(&skill.art_description),
        if skill.observed { "Referenced" } else { "Unexercised" },
    ));
    if !skill.issues.is_empty() {
        for issue in &skill.issues {
            text.push_str(&format!("- Parser issue: `{}`\n", inline(issue)));
        }
        text.push('\n');
    }
    text.push_str("| Slot | Behavior key | Raw behavior | Registry | Semantic owner | Capture | Target / limits | Route | References |\n|---|---|---|---|---|---|---|---|---|\n");
    for slot in &skill.slots {
        text.push_str(&format!(
            "| {} | {} `{}` | `{}` | {} | {} | {} | `{}` / `{}`; limit={}; round={}; conditionTarget=`{}` | `{}` | skills={:?}; buffs={:?} |\n",
            slot.number,
            slot.behavior.opcode.map_or_else(|| "—".to_owned(), |id| id.to_string()),
            escape(&slot.behavior.type_name),
            inline(&slot.behavior.raw),
            slot.behavior.registry,
            slot.behavior.semantic,
            slot.behavior.observation,
            inline(&slot.behavior_target),
            inline(&slot.behavior.detail),
            slot.limit,
            slot.round_limit,
            inline(&slot.condition_target),
            inline(&slot.route),
            slot.referenced_skills,
            slot.referenced_buffs,
        ));
        for condition in &slot.conditions {
            text.push_str(&format!(
                "| ↳ condition | {} `{}` | `{}` | {} | {} | {} | {} | `{}` | — |\n",
                condition
                    .opcode
                    .map_or_else(|| "—".to_owned(), |id| id.to_string()),
                escape(&condition.type_name),
                inline(&condition.raw),
                condition.registry,
                condition.semantic,
                condition.observation,
                inline(&condition.detail),
                inline(&slot.route),
            ));
        }
    }
    text.push('\n');
}

fn render_buff(text: &mut String, buff: &Buff) {
    text.push_str(&format!(
        "#### Buff {} — {}\n\n- Description: {}\n- Duration: {}\n- Type: {}\n- Capture: {}\n\n",
        buff.id,
        escape(&buff.name),
        prose(&buff.description),
        buff.duration,
        buff.type_id,
        if buff.observed {
            "Referenced"
        } else {
            "Unexercised"
        },
    ));
    if buff.acts.is_empty() {
        text.push_str("No configured buff acts.\n\n");
        return;
    }
    text.push_str("| Buff act key | Raw feature | Registry | Semantic owner | Capture | Effect time / event | Destination | Duration owner | Wire |\n|---|---|---|---|---|---|---|---|---|\n");
    for act in &buff.acts {
        text.push_str(&format!(
            "| {} `{}` | `{}` | {} | {} | {} | {} / `{}` | `{}` | {} | {} |\n",
            act.node
                .opcode
                .map_or_else(|| "—".to_owned(), |id| id.to_string()),
            escape(&act.node.type_name),
            inline(&act.node.raw),
            act.node.registry,
            act.node.semantic,
            act.node.observation,
            act.effect_time,
            inline(&act.event),
            inline(&act.destination),
            act.owns_duration,
            act.wire,
        ));
    }
    text.push('\n');
}

#[derive(Default)]
struct Links(BTreeMap<String, Vec<String>>);

impl Links {
    fn load(output: &Path) -> Result<Self> {
        let path = output.join("battle-support-links.json");
        if !path.is_file() {
            return Ok(Self::default());
        }
        let contents = fs::read_to_string(&path).context("read battle-support-links.json")?;
        let links: BTreeMap<String, Vec<String>> =
            serde_json::from_str(&contents).context("parse battle-support-links.json")?;
        for urls in links.values() {
            for url in urls {
                if !valid_github_link(url) {
                    anyhow::bail!("invalid issue or pull-request URL in battle-support-links.json");
                }
            }
        }
        Ok(Self(links))
    }

    fn render(&self, key: &str) -> String {
        self.0.get(key).map_or_else(
            || "—".to_owned(),
            |urls| {
                urls.iter()
                    .enumerate()
                    .map(|(index, url)| format!("[{}]({url})", index + 1))
                    .collect::<Vec<_>>()
                    .join(", ")
            },
        )
    }
}

fn write(path: impl AsRef<Path>, contents: &str) -> Result<()> {
    let path = path.as_ref();
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)
        .with_context(|| format!("create new report file {}", path.display()))?;
    file.write_all(contents.as_bytes())
        .with_context(|| format!("write {}", path.display()))
}

fn valid_github_link(url: &str) -> bool {
    let Some(path) = url.strip_prefix("https://github.com/") else {
        return false;
    };
    let parts = path.split('/').collect::<Vec<_>>();
    parts.len() == 4
        && parts[0].chars().all(github_path_char)
        && !parts[0].is_empty()
        && parts[1].chars().all(github_path_char)
        && !parts[1].is_empty()
        && matches!(parts[2], "issues" | "pull")
        && !parts[3].is_empty()
        && parts[3].chars().all(|character| character.is_ascii_digit())
}

fn github_path_char(character: char) -> bool {
    character.is_ascii_alphanumeric() || matches!(character, '-' | '_' | '.')
}

fn escape(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}

fn inline(value: &str) -> String {
    escape(value).replace('`', "'")
}

fn prose(value: &str) -> String {
    let value = escape(value);
    if value.is_empty() {
        "—".to_owned()
    } else {
        value
    }
}

fn chapter_label(chapter: i32) -> String {
    if (101..=113).contains(&chapter) {
        format!("Chapter {}", chapter % 100)
    } else if (201..=213).contains(&chapter) {
        format!("Hard Chapter {}", chapter % 100)
    } else {
        format!("Config Chapter {chapter}")
    }
}

fn chapter_anchor(chapter: i32) -> String {
    chapter_label(chapter)
        .to_ascii_lowercase()
        .replace(' ', "-")
}

fn chapter_order(chapter: i32) -> (u8, i32) {
    if (101..=113).contains(&chapter) {
        (0, chapter)
    } else if (201..=213).contains(&chapter) {
        (1, chapter)
    } else {
        (2, chapter)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn chapter_links_match_rendered_heading_anchors() {
        assert_eq!(chapter_anchor(101), "chapter-1");
        assert_eq!(chapter_anchor(205), "hard-chapter-5");
        assert_eq!(chapter_anchor(999), "config-chapter-999");
    }

    #[test]
    fn only_plain_github_issue_and_pull_links_are_accepted() {
        for url in [
            "https://github.com/yoncodes/enigma/issues/574",
            "https://github.com/yoncodes/enigma/pull/575",
        ] {
            assert!(valid_github_link(url));
        }
        for url in [
            "file:///private/report",
            "https://github.com/yoncodes/enigma/issues/574)",
            "https://github.com/yoncodes/enigma/issues/574|oops",
            "https://github.com/yoncodes/enigma/discussions/574",
            "https://example.com/yoncodes/enigma/issues/574",
        ] {
            assert!(!valid_github_link(url));
        }
    }
}
